# CONFIGSERVER MICROSERVICE : Default Setting -----------------------------------------------------
# ********************************************************************************************
server.port: 8012
spring.application.name: config-server


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: 'C:\venga\devops-venga\appconf'
